services:

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: user_admin
      POSTGRES_PASSWORD: over123
      TZ: "Asia/Novosibirsk"
    ports:
      - 5432:5432
    container_name: overgres
    volumes:
      - ./postgresql/:/var/lib/postgresql/data
  fastapi:
    build:
      context: .
      dockerfile: Dockerfile
    image: local/faspapi
    restart: always
    environment:
      TZ: "Asia/Novosibirsk"
    ports:
      - 8000:8000
    container_name: fastapi
    volumes:
      - ./app/:/code/app/